name: meat
channels:
  - sci-bots
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - numpy=1.19.4
  - opencv=4.1.1
  - paho-mqtt=1.3.1
  - pandas=1.1.3
  - pip=20.2.4
  - pyqt=5.9.2
  - python=3.6.12
  - wheel=0.35.1
  - pip:
    - pyaudio==0.2.11
    - pocketsphinx==0.1.15
    - setuptools==50.3.2
    - pocketsphinx==0.1.15
    - speechrecognition==3.8.1

