name: MEAT CI

on: [push]

jobs:
  format:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v1
      - name: Check no formatting errors
        run: |
          bash run_clang.sh
  build:
    needs: [format]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
   